version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "javascript"
    versioning-strategy: increase
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      major:
        applies-to: version-updates
        update-types:
          - major
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions: [">=25.0.0"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
      - "CI"
    versioning-strategy: increase
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"
