name: Test & Deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - php: 8.0
            can-fail: false
          - php: 8.1
            can-fail: true

    name: "Test Application - PHP ${{ matrix.php }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: curl, dom, libxml, mbstring, pcntl, pdo, sqlite, pdo_sqlite, zip
          coverage: none

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Setup .env
        run: cp .env.example .env

      - name: Install Composer Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install --no-interaction

      - name: Install NPM Dependencies
        run: npm ci

      - name: Compile Assets
        run: npm run production

      - name: Generate App Key
        run: php artisan key:generate

      - name: Execute Tests
        run: vendor/bin/phpunit --verbose

  deploy:
    needs: test
    if: github.ref == 'refs/heads/production'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Envoyer
        run: curl ${{ secrets.ENVOYER_HOOK }}?sha=${{ github.sha }}
